
name: nodejs
# on: [push,workflow_dispatch]
# on:
#   - push
#   - workflow_dispatch  //
on:
  push:
    branches:
      - main
      - feature/**
    paths-ignore:
      - '.github/workflows/*'
      - README.md
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4

      - name: install Node20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: print node version
        run: node -v

      - name: install dependencies
        run: npm ci

      - name: run test case
        run: npm run test
        
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4

      - name: install Node20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: print node version
        run: node -v

      - name: install dependencies
        run: npm ci

      - name: build project
        run: npm run build 

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist 

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:    
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist 

      - name: deploy
        run: echo "deployed successfully"

       
       